Script started on Mon 22 Feb 2016 03:38:44 PM EST
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ cat   cat   cat year_codes.java
/* year_codes.java is a driver for function yearCode().
 * Begun by: Serita Nelesen, for CS 214 at Calvin College.
 * By: Zach Wibbenmeyer
 * Date: February 24, 2016
 ****************************************************************/
import java.util.Scanner;

public class year_codes {

   public static void main(String[] args) {
      Scanner keyboard = new Scanner(System.in);
      System.out.println("\nEnter your academic year: "); // prompt

      String year = keyboard.next();       // read year
      System.out.println(yearCode(year)); // display its code
   }

   /***************************************************************
    * yearCode() converts an academic year into its integer code. *
    * Receive: year, a string.
    * PRE: year is one of {freshman, sophomore, junior, or senior}.
    * Return: the integer code corresponding to year.
    */

   public static int yearCode(String year) {
      if (year.equals("freshman"))
         return 1;
      else if (year.equals("sophomore"))
	 return 2;
      else if (year.equals("junior"))
	 return 3;
      else if (year.equals("senior"))
	 return 4;
      else
	 return 0;
   }

}
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ javac j   year_codes.java
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ jav   java e year_codes

Enter your academic year: 
freshman
1
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ java year_codes

Enter your academic year: 
sophomore
2
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ java year_codes

Enter your academic year: 
junior
3
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ java year_codes

Enter your academic year: 
senior
4
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ java year_codes

Enter your academic year: 
nah
0
zdw3@eckert-mauchly:~/workspace/cs214/labs/03$ exit

Script done on Mon 22 Feb 2016 03:39:37 PM EST
